"""
app/models/note.py
==================
Note: polymorphic note attached to exactly one of Company, Contact, or Meeting.
Enforced at the DB level via CHECK constraint (see schema.sql).
"""

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, CheckConstraint, ForeignKey, Text, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, BaseModel

if TYPE_CHECKING:
    from app.models.company import Company
    from app.models.contact import Contact
    from app.models.meeting import Meeting
    from app.models.user import User


class Note(Base, BaseModel):
    """
    A note attached to exactly one entity (company, contact, or meeting).
    Can be authored by a human user or generated by AI (is_ai_generated=True).
    """

    __tablename__ = "notes"
    __table_args__ = (
        CheckConstraint(
            "(company_id IS NOT NULL)::int + (contact_id IS NOT NULL)::int "
            "+ (meeting_id IS NOT NULL)::int = 1",
            name="notes_entity_check",
        ),
    )

    author_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
    )
    is_ai_generated: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false"), default=False
    )

    # ── Polymorphic FK — exactly one must be set ──────────────────────────────
    company_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("companies.id", ondelete="CASCADE")
    )
    contact_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("contacts.id", ondelete="CASCADE")
    )
    meeting_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("meetings.id", ondelete="CASCADE")
    )

    content: Mapped[str] = mapped_column(Text, nullable=False)
    pinned: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false"), default=False
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    author: Mapped[User | None] = relationship("User", lazy="select")
    company: Mapped[Company | None] = relationship(
        "Company",
        back_populates="notes",
        lazy="select",
        foreign_keys=[company_id],
    )
    contact: Mapped[Contact | None] = relationship(
        "Contact",
        back_populates="note_records",
        lazy="select",
        foreign_keys=[contact_id],
    )
    meeting: Mapped[Meeting | None] = relationship(
        "Meeting",
        back_populates="note_records",
        lazy="select",
        foreign_keys=[meeting_id],
    )

    # ── Factory helpers ───────────────────────────────────────────────────────

    @classmethod
    def for_company(
        cls, company_id: uuid.UUID, content: str, author_id: uuid.UUID | None = None,
        is_ai_generated: bool = False,
    ) -> Note:
        return cls(
            company_id=company_id, content=content,
            author_id=author_id, is_ai_generated=is_ai_generated,
        )

    @classmethod
    def for_contact(
        cls, contact_id: uuid.UUID, content: str, author_id: uuid.UUID | None = None,
        is_ai_generated: bool = False,
    ) -> Note:
        return cls(
            contact_id=contact_id, content=content,
            author_id=author_id, is_ai_generated=is_ai_generated,
        )

    @classmethod
    def for_meeting(
        cls, meeting_id: uuid.UUID, content: str, author_id: uuid.UUID | None = None,
        is_ai_generated: bool = False,
    ) -> Note:
        return cls(
            meeting_id=meeting_id, content=content,
            author_id=author_id, is_ai_generated=is_ai_generated,
        )
